### ISSUE TITLE
Checklist for changes prior to relaunch

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/people-directory#26]
Here's what we'd like to have before deploying this again:

- [x] All references / modules involving EDIR, LDAP and Feeds removed (we're not using them)
- [x] All views, styles, templates etc that reference EDIR should be removed or modified to only use the proper current node type.
- [x] Remove Feeds module completely.
- [x] Remove taxonomy of expertise, remove from Person template and fields
- [x] Remove EDIR from People fields
- [x] Remove the relationship in View > Advanced which references the expertise taxonomy. Reason: This is _contact info_ not _professional classification_
 - [x] Apply all core and security updates

**Comment by brucecrevensten** [comment]
For fixing the PHP templates: we want to replace everything that looks like this:

```php
$node->field_edir_name['und'][0]['entity']->field_phone;
```

...with something that looks like this:

```php
$node->field_phone
```

So, we're remapping the display from fields using EDIR to fields instead stored in the Person content type.

Field mapping [here](https://docs.google.com/spreadsheets/u/1/d/1lqMIQSsGrksaPaW1hTMk0OkWYfIZw5nwB2I32hDOYMo/edit?usp=sharing).
