### ISSUE TITLE
Relaunch checklist

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/people-directory#27]
For launch:

 - [ ] Ensure that nobody can log in from outside UAF network
 - [x] Figure out proper hosting on our OS server
 - [ ] Remap any IPs/DNS entries as required to integrate this properly on our OS server
 - [ ] Set FQDN
 - [ ] Set up virtual host or other Apache config properly
 - [ ] Secure MySQL as required
 - [ ] Launch!
